Server:
  port: 8080

#mybatis配置
mybatis:
  type-aliases-package: com.dayu.jkapp.server.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/health?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
